# Architecture
arch: vgg19_cifar100
pruned_model: ./ckpt/vgg19_cifar100.pt

# ===== Dataset ===== #
data_path: ./datasets/cifar
data_set: cifar100

eval_batch_size: 256

# ===== Sparsity ===== #
conv_type: PretrainConv

