# Architecture
arch: resnet32_cifar10
pruned_model: ./ckpt/resnet32_cifar10.pt

# ===== Dataset ===== #
data_path: ./datasets/cifar
data_set: cifar10


# ===== Sparsity ===== #
conv_type: PretrainConv

