# Architecture
arch: resnet32_cifar100
pretrained_model: ./pre-train/resnet32_cifar100.pt

# ===== Dataset ===== #
data_path: ./datasets/cifar
data_set: cifar100
job_dir: ./experiment/resnet32_cifar100/95sparsity30epoch

# ===== Learning Rate Policy ======== #
optimizer: sgd
lr: 0.1

# ===== Network training config ===== #
num_epochs: 30
weight_decay: 0.0005
momentum: 0.9
train_batch_size: 256
eval_batch_size: 256
prune_rate: 0.95 # Override

# ===== Sparsity ===== #
conv_type: PretrainConv
freeze_weights: True


# ===== Hardware setup ===== #
workers: 20
